
[env]
TERM = "xterm-256color"

#[colors.normal]
#blue = "0x1E6E77"

#[colors.bright]
#blue = "0x28939F"

#[colors.primary]
#background = "0x1a1b26"
#foreground = "0xe0def4"

#[colors.selection]
#background = "0x2A2738"
#text = "CellForeground"

#[colors.vi_mode_cursor]
#cursor = "0x796268"
#text = "0x191724"

[font]
size = 11.0

[font.bold]
family = "Hasklug Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "Hasklug Nerd Font"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    {key = "F", mods = "Control|Shift", action = "ToggleFullscreen"}
]

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.8
blur = true

[window.padding]
x = 16
y = 16

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/color-schema.toml"
]

